### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by CoolSmit007** [Xu-Justin/DeepFaceDrawing-Weight#1]
I tried pulling the dvc the following error occured:

unexpected error - : <HttpError 404 when requesting https://www.googleapis.com/drive/v2/files/1TLdS7VnFteXLnj77b9pie7GK1x4HHjKz?fields=driveId&supportsAllDrives=true&alt=json returned "File not found: 1TLdS7VnFteXLnj77b9pie7GK1x4HHjKz". Details: "[{'message': 'File not found: 1TLdS7VnFteXLnj77b9pie7GK1x4HHjKz', 'domain': 'global', 'reason': 'notFound', 'location': 'file', 'locationType': 'other'}]">

**Comment by Xu-Justin** [comment]
Hi @CoolSmit007 , 
I have just re-tested `dvc pull` and it's still working.

Your error might be caused by permission issues. I'm not sure how to solve it right now. Otherwise, you can just directly download from my Google Drive.

https://drive.google.com/file/d/1pERwQOaM0uzaIkufCYNrIE5aR-hK3ANs/view?usp=drive_link

### Directory Structure
```
weight
├── DeepFaceDrawing
│   ├── CE
│   │   ├── background
│   │   │   ├── decoder.pth
│   │   │   ├── encoder.pth
│   │   │   └── output.pth
│   │   ├── left_eye
│   │   │   ├── decoder.pth
│   │   │   ├── encoder.pth
│   │   │   └── output.pth
│   │   ├── mouth
│   │   │   ├── decoder.pth
│   │   │   ├── encoder.pth
│   │   │   └── output.pth
│   │   ├── nose
│   │   │   ├── decoder.pth
│   │   │   ├── encoder.pth
│   │   │   └── output.pth
│   │   └── right_eye
│   │       ├── decoder.pth
│   │       ├── encoder.pth
│   │       └── output.pth
│   ├── FM
│   │   ├── background
│   │   │   ├── decoder.pth
│   │   │   └── output.pth
│   │   ├── left_eye
│   │   │   ├── decoder.pth
│   │   │   └── output.pth
│   │   ├── mouth
│   │   │   ├── decoder.pth
│   │   │   └── output.pth
│   │   ├── nose
│   │   │   ├── decoder.pth
│   │   │   └── output.pth
│   │   └── right_eye
│   │       ├── decoder.pth
│   │       └── output.pth
│   └── IS
│       ├── discriminator_1.pth
│       ├── discriminator_2.pth
│       ├── discriminator_3.pth
│       └── generator.pth
└── sketch_simplification
    └── model_gan.pth
```
